### ISSUE TITLE
Please update packagist as well

### ISSUE THREAD

**Issue by susonwaiba** [designmynight/laravel-mongodb-passport#20] opened 2019-04-01 16:03 UTC
hi, I am adding this package but seems like you have only updated your GIT repo.
So, Please update your https://packagist.org/packages/designmynight/laravel-mongodb-passport as well.
Thanks for packages. Great help

**Comment by matiaspub** [comment] 2019-06-13 19:02
that's can help while we waitinghttps://www.sitepoint.com/quick-tip-composer-github-develop-packages-interactively/

**Comment by matiaspub** [comment] 2019-06-13 19:04
Duplicate of #19

**Closed as completed** 2020-05-14 04:58 UTC
